'use strict';
import { S } from './state.js';

export const T = {
  fr: {
    title:'OptiCoupe', save:'💾 Sauvegarder', load:'📂 Ouvrir', export:'📄 Bon de débit',
    projet:'Projet', panel:'Panneau standard', pieces:'Pièces à découper',
    projname:'Nom du projet', client:'Client', mat:'Matériau', thick:'Ép. (mm)', color:'Finition',
    lMatDesc:'Description matériau', lMatUrl:'Lien produit (URL)', lComments:'Commentaires bon de débit',
    matDesc:'Description matériau', comments:'Commentaires',
    matDescEmpty:'Cliquer pour ajouter une description...', commentsEmpty:'Cliquer pour ajouter des commentaires...',
    pw:'Largeur (mm)', ph:'Hauteur (mm)', kerf:'Trait scie (mm)', area:'Surface (m²)',
    grain:'Respecter le fil du bois (pas de rotation)',
    thName:'Nom', thL:'L mm', thH:'H mm', thQ:'Qté',
    addPiece:'+ Pièce', example:'Exemple', clear:'Vider', addsize:'+',
    csvIn:'⬆ Import CSV', csvOut:'⬇ Export CSV',
    calc:'▶ Optimiser la découpe',
    emptyMsg:'Ajoutez vos pièces et cliquez sur <strong>Optimiser la découpe</strong> pour comparer les 4 stratégies.',
    a_maxrects:'🎯 Densité max',    a_maxrects_d:'MaxRects — minimum de pertes',
    a_llas:'📏 Chutes longues',     a_llas_d:'Guillotine — bandes réutilisables',
    a_shelf:'▬ Chutes larges',      a_shelf_d:'Par rangées — grandes chutes en bas',
    a_slas:'⚖️ Équilibré',          a_slas_d:'Guillotine — bon compromis',
    panels:'panneau(x)', pcs:'pièce(s)', used:'utilisé',
    statPanels:'Panneaux', statEff:'Rendement', statUsed:'Surface utile',
    statWaste:'Chutes / perte', statBig:'+ grande chute',
    showOffcuts:'Afficher les chutes :', hideOffcuts:'✓ Visible', shownOffcuts:'Masqué',
    dragHint:'Glissez les pièces pour ajuster · ↻ clic droit = pivoter · glisser entre panneaux possible',
    errBig:'"%(n)s" (%(w)s×%(h)smm) est plus grande que le panneau.',
    errNoPieces:'Ajoutez au moins une pièce avec des dimensions valides.',
    errPanel:'Dimensions du panneau invalides.',
    tipOffcut:'Chute :',
    bonTitle:'BON DE DÉBIT', bonDate:'Date :', bonRef:'Réf. :', bonScierie:'Document à remettre à votre scierie',
    bonPanel:'Panneau :', bonQtyPanels:'Panneaux nécessaires :', bonKerf:'Trait de scie :', bonEff:'Rendement global :',
    bonListTitle:'Liste des pièces', bonPlanTitle:'Plans de coupe',
    bonNum:'N°', bonName:'Désignation', bonL:'Longueur', bonW:'Largeur', bonThk:'Ép.', bonObs:'Observations',
    bonComments:'Commentaires', bonPanelLabel:'Panneau', bonRotated:'Pivoté',
    bonFooter:'Généré par OptiCoupe',
  },
  en: {
    title:'OptiCoupe', save:'💾 Save', load:'📂 Open', export:'📄 Cut Sheet',
    projet:'Project', panel:'Standard Sheet', pieces:'Pieces to cut',
    projname:'Project name', client:'Client', mat:'Material', thick:'Thk (mm)', color:'Finish',
    lMatDesc:'Material description', lMatUrl:'Product link (URL)', lComments:'Cutting order notes',
    matDesc:'Material description', comments:'Notes',
    matDescEmpty:'Click to add a description...', commentsEmpty:'Click to add notes...',
    pw:'Width (mm)', ph:'Height (mm)', kerf:'Blade kerf (mm)', area:'Area (m²)',
    grain:'Respect grain direction (no rotation)',
    thName:'Name', thL:'W mm', thH:'H mm', thQ:'Qty',
    addPiece:'+ Piece', example:'Example', clear:'Clear', addsize:'+',
    csvIn:'⬆ Import CSV', csvOut:'⬇ Export CSV',
    calc:'▶ Optimize cutting',
    emptyMsg:'Add your pieces and click <strong>Optimize cutting</strong> to compare 4 strategies.',
    a_maxrects:'🎯 Max Density',  a_maxrects_d:'MaxRects — minimum waste',
    a_llas:'📏 Long offcuts',     a_llas_d:'Guillotine — reusable strips',
    a_shelf:'▬ Wide offcuts',     a_shelf_d:'Row-based — large bottom strips',
    a_slas:'⚖️ Balanced',         a_slas_d:'Guillotine — good compromise',
    panels:'sheet(s)', pcs:'piece(s)', used:'used',
    statPanels:'Sheets', statEff:'Efficiency', statUsed:'Used area',
    statWaste:'Offcuts / waste', statBig:'Largest offcut',
    showOffcuts:'Show offcuts:', hideOffcuts:'✓ Visible', shownOffcuts:'Hidden',
    dragHint:'Drag pieces to adjust · ↻ right-click = rotate · cross-panel drag supported',
    errBig:'"%(n)s" (%(w)s×%(h)smm) is larger than the sheet.',
    errNoPieces:'Add at least one piece with valid dimensions.',
    errPanel:'Invalid sheet dimensions.',
    tipOffcut:'Offcut:',
    bonTitle:'CUTTING ORDER', bonDate:'Date:', bonRef:'Ref.:', bonScierie:'Document to submit to your cutting service',
    bonPanel:'Sheet:', bonQtyPanels:'Sheets needed:', bonKerf:'Blade kerf:', bonEff:'Overall efficiency:',
    bonListTitle:'Piece list', bonPlanTitle:'Cutting layouts',
    bonNum:'#', bonName:'Description', bonL:'Length', bonW:'Width', bonThk:'Thk', bonObs:'Notes',
    bonComments:'Notes', bonPanelLabel:'Sheet', bonRotated:'Rotated',
    bonFooter:'Generated by OptiCoupe',
  },
};

export const t   = k => T[S.lang][k] || k;
export const fmt = (k, vars) => t(k).replace(/%\((\w+)\)s/g, (_, n) => vars[n] ?? '');

export function setLang(l) {
  S.lang = l;
  document.getElementById('btn-fr').className = 'btn-lang' + (l === 'fr' ? ' active' : '');
  document.getElementById('btn-en').className = 'btn-lang' + (l === 'en' ? ' active' : '');
  applyLang();
}

export function applyLang() {
  const ids = {
    'h-title':'title','h-save':'save','h-load':'load','h-export':'export',
    's-projet':'projet','s-panel':'panel','s-pieces':'pieces',
    'l-projname':'projname','l-client':'client','l-mat':'mat','l-thick':'thick','l-color':'color',
    'l-mat-desc':'lMatDesc','l-mat-url':'lMatUrl','l-comments':'lComments',
    'l-pw':'pw','l-ph':'ph','l-kerf':'kerf','l-area':'area','l-grain':'grain',
    'th-name':'thName','th-l':'thL','th-h':'thH','th-q':'thQ',
    'btn-add':'addPiece','btn-ex':'example','btn-clear':'clear',
    'btn-csv-in':'csvIn','btn-csv-out':'csvOut','btn-calc':'calc','btn-addsize':'addsize',
  };
  for (const [id, key] of Object.entries(ids)) {
    const el = document.getElementById(id);
    if (el) el.textContent = t(key);
  }
  document.getElementById('empty-msg').innerHTML = t('emptyMsg');
  document.getElementById('modal-cancel').textContent = S.lang === 'fr' ? 'Annuler' : 'Cancel';
  document.documentElement.lang = S.lang;
}
